version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - nginx_network

  web:
    build: .
    image: docker_sunabaco_web:latest
    environment:
      - DISPLAY=$DISPLAY_MAC
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    # devices:
    #   - /dev/video0:/dev/video0
    volumes:
      - .:/sunabaco_app
      - ~/V4L2:/dev/video0
      - ~/vagrant/data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority
      - ./nginx/gunicorn:/var/run/gunicorn
    tty: true
    command: python manage.py runsslserver 0.0.0.0:8000 --certificate foobar.crt --key foobar.key
    ports:
      - "8000:5000"
    depends_on:
      - db
    networks:
      - nginx_network

  app:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: docker_sunabaco_app:latest
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/gunicorn:/var/run/gunicorn
    ports:
      - "5000:80"
    depends_on:
      - web
    restart: always
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

