# Generated by Django 3.1.2 on 2020-12-13 16:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='タイトル')),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('genre', models.CharField(choices=[('デザイン', 'デザイン'), ('ビジネス', 'ビジネス'), ('プログラミング', 'プログラミング'), ('社会', '社会'), ('その他', 'その他')], max_length=21, verbose_name='本のジャンル')),
                ('Author', models.CharField(max_length=32, verbose_name='本の著者')),
                ('body', models.TextField(max_length=512, verbose_name='本の説明')),
                ('image', models.ImageField(upload_to='upload_to_book', verbose_name='本のイメージ')),
                ('lending', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='レンタルモード')),
                ('book_status', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='本の貸し出し状態')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(editable=False)),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='サンプル項目1 日付')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
            ],
        ),
    ]
