# Generated by Django 3.1.2 on 2020-12-17 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookimage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='タイトル')),
                ('genre', models.CharField(choices=[('デザイン', 'デザイン'), ('ビジネス', 'ビジネス'), ('プログラミング', 'プログラミング'), ('社会', '社会'), ('その他', 'その他')], max_length=21, verbose_name='本のジャンル')),
                ('Author', models.CharField(max_length=32, verbose_name='本の著者')),
                ('body', models.TextField(max_length=512, null=True, verbose_name='本の説明')),
                ('image', models.ImageField(upload_to='upload_to_book', verbose_name='本のイメージ')),
                ('lending', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='レンタルモード')),
                ('book_status', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='本の貸し出し状態')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(choices=[(1, '★1'), (2, '★2'), (3, '★3'), (4, '★4'), (5, '★5')], verbose_name='評価点')),
                ('body', models.TextField(max_length=512, null=True, verbose_name='本の感想')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunabaco_book.bookimage', verbose_name='評価対象の本')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lending_user_id', models.UUIDField(editable=False)),
                ('return_date', models.DateField(blank=True, verbose_name='返却日 日付')),
                ('book_id', models.UUIDField(editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunabaco_book.bookimage')),
            ],
        ),
    ]
