# Generated by Django 3.1.2 on 2020-12-12 09:18

from django.db import migrations
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', register.models.CustomUserManager()),
            ],
        ),
    ]
